/*
 * generated by Xtext 2.12.0
 */
package it.cnr.istc.ghost.ide

import com.google.inject.Guice
import it.cnr.istc.ghost.GhostRuntimeModule
import it.cnr.istc.ghost.GhostStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GhostIdeSetup extends GhostStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GhostRuntimeModule, new GhostIdeModule))
	}
	
}
