/*
 * generated by Xtext 2.12.0
 */
package it.cnr.istc.ghost.tests

import com.google.inject.Inject
import it.cnr.istc.ghost.ghost.Ghost
import it.cnr.istc.ghost.ghost.GhostPackage
import it.cnr.istc.ghost.validation.GhostValidator
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(GhostInjectorProvider)
class GhostExpressionValidatorTest2{

	@Inject extension ParseHelper<Ghost>
	@Inject extension ValidationTestHelper
	
	@Test
	def void testComparisonDiffTypes() {
		val model = '''
type e = enum(EN1,EN2);
comp c : sv (
	A -> 1 = EN1;
)
		'''.parse;
		model.assertWarning(GhostPackage.Literals.EXPRESSION,
			GhostValidator.COMPARISON_DIFFERENT_TYPES);
	}
	
	@Test
	def void testBoolNum() {
		val model = '''
comp c : sv (
	A -> 1 + (1 > 0);
)
		'''.parse;
		model.assertWarning(GhostPackage.Literals.EXPRESSION,
			GhostValidator.BOOLEAN_TO_NUMERIC);
	}
	
	@Test
	def void testExpected1() {
		val model = '''
type e = enum(EN1,EN2);
comp c : sv (
	A -> 1 + EN1;
)
		'''.parse;
		model.assertError(GhostPackage.Literals.EXPRESSION,
			GhostValidator.EXPECTED_TYPE);
	}
	
	@Test
	def void testExpected2() {
		val model = '''
comp c : sv (
	A -> start(A) + 1;
)
		'''.parse;
		model.assertError(GhostPackage.Literals.EXPRESSION,
			GhostValidator.EXPECTED_TYPE);
	}
	
	//Unused variables
	@Test
	def void testUnusedVar1() {
		val model = '''
comp c : sv (
	A -> var x = 12;
);
		'''.parse;
		model.assertWarning(GhostPackage.Literals.TRANS_CONSTR_BODY, GhostValidator.UNUSED_VAR);
	}
	
	@Test
	def void testUnusedVar2() {
		val model = '''
comp c : sv (
	A -> (var x = 12, x > 10);
);
		'''.parse;
		model.assertNoIssues();
	}
	
	//Useless expressions
	@Test
	def void testUselessExp1() {
		val model = '''
comp c : sv (
	A -> 15
);
		'''.parse;
		model.assertWarning(GhostPackage.Literals.TRANS_CONSTR_BODY, GhostValidator.USELESS_EXPRESSION);
	}
	
	@Test
	def void testUselessExp2() {
		val model = '''
comp c : sv (
	A, B
synchronize:
	A -> B
);
		'''.parse;
		model.assertWarning(GhostPackage.Literals.SYNC_BODY, GhostValidator.USELESS_EXPRESSION);
	}
	
	@Test
	def void testUselessExp3() {
		val model = '''
type e = enum(E1,E2);
comp c : sv (
	A -> E1
);
		'''.parse;
		model.assertWarning(GhostPackage.Literals.TRANS_CONSTR_BODY, GhostValidator.USELESS_EXPRESSION);
	}
	
	@Test
	def void testNotUselessExp1() {
		val model = '''
comp c : sv (
	A -> var x = 15
);
		'''.parse;
		model.assertNoIssue(GhostPackage.Literals.TRANS_CONSTR_BODY, GhostValidator.USELESS_EXPRESSION);
	}
	
	@Test
	def void testNotUselessExp2() {
		val model = '''
comp c : sv (
	A -> B, B
);
		'''.parse;
		model.assertNoIssue(GhostPackage.Literals.TRANS_CONSTR_BODY, GhostValidator.USELESS_EXPRESSION);
	}
	
	@Test
	def void testNotUselessExp3() {
		val model = '''
comp c : sv (
	A -> 10 < 15
);
		'''.parse;
		model.assertNoIssue(GhostPackage.Literals.TRANS_CONSTR_BODY, GhostValidator.USELESS_EXPRESSION);
	}
	
	@Test
	def void testNotUselessExp4() {
		val model = '''
comp c : sv (
	A, B
synchronize:
	A -> EQUALS B
);
		'''.parse;
		model.assertNoIssue(GhostPackage.Literals.SYNC_BODY, GhostValidator.USELESS_EXPRESSION);
	}
	
	
}
