/*
 * generated by Xtext 2.10.0
 */
package it.cnr.istc.ghost


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GhostStandaloneSetup extends GhostStandaloneSetupGenerated {

	def static void doSetup() {
		new GhostStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
