/*
 * generated by Xtext 2.12.0
 */
package it.cnr.istc.ghost.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class GhostWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public GhostWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
